version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.5
    container_name: keycloak
    command:
      - "start-dev"
      - "--import-realm"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/video-realm.json
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
    ports:
      - "8081:8080"
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT=http://localstack:4566
      - S3_BUCKET=bucket-videos
      - SQS_BUCKET=work-queue
      - DB_PASSWORD=password
      - DB_URL=jdbc:postgresql://postgres:5432/video_db
      - DB_USERNAME=user
      - ISSUER_URL=http://keycloak:8080/realms/video
      - JWK_URI=http://keycloak:8080/realms/video/protocol/openid-connect/certs
    ports:
      - "9090:9090"
    networks:
      - app-network

volumes:
  localstack_data:

networks:
  app-network:
    external: true
