version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,sqs
      - EDGE_PORT=4566
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./localstack/init:/etc/localstack/init/ready.d
      - localstack_data:/var/lib/localstack
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    depends_on:
      - localstack
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_SQS_QUEUE_URL=http://localhost:4566/000000000000/video-queue
      - SPRING_PROFILES_ACTIVE=local
      - AWS_ENDPOINT=http://localhost:4566
      - EMAIL=test@gmail.com
      - EMAIL_PASSWORD=123
    ports:
      - "8090:8090"
    networks:
      - app-network

volumes:
  localstack_data:

networks:
  app-network:
    driver: bridge
