version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,sqs
      - EDGE_PORT=4566
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./localstack/init:/etc/localstack/init/ready.d
      - localstack_data:/var/lib/localstack
    networks:
      - app-network
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.5
    container_name: keycloak
    command:
      - "start-dev"
      - "--import-realm"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/video-realm.json
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
    ports:
      - "8081:8080"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    depends_on:
      - localstack
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT=http://localhost:4566
      - S3_BUCKET=meus-videos
      - SQS_BUCKET=video-queue
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  localstack_data:

networks:
  app-network:
    driver: bridge
