spring:
  application:
    name: fast-food
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:schema.sql
server:
  servlet:
    context-path: /video-api

springdoc:
  api-docs:
    path: /v1/api-docs

  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha

app:
  api:
    gateway:
      url: ${API_GATEWAY_URL}