spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  application:
    name: fast-food
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:schema.sql
server:
  servlet:
    context-path: /video-api

springdoc:
  api-docs:
    path: /v1/api-docs

  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
cloud:
  aws:
    credentials:
      accessKey: ${AWS_SECRET_ACCESS_KEY:test}
      secretKey: ${AWS_SECRET_ACCESS_KEY:test}
    region:
      static: ${AWS_SECRET_ACCESS_KEY:us-east-1}
    stack:
      auto: false
    sqs:
      endpoint: ${AWS_ENDPOINT:http://localhost:4566}
    s3:
      endpoint: ${AWS_ENDPOINT:http://localhost:4566}
aws:
  s3:
    bucket: meus-videos